"""Migration

Revision ID: 2859f78fe8af
Revises: c18908afc042
Create Date: 2019-05-27 09:07:48.632335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2859f78fe8af'
down_revision = 'c18908afc042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
