"""Migration

Revision ID: 30542f6de769
Revises: 2859f78fe8af
Create Date: 2019-05-27 10:24:50.963571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30542f6de769'
down_revision = '2859f78fe8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
