"""Migration

Revision ID: c18908afc042
Revises: 8d9893b6f855
Create Date: 2019-05-27 08:59:50.303361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18908afc042'
down_revision = '8d9893b6f855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
