"""Migration

Revision ID: fba55687c999
Revises: 30542f6de769
Create Date: 2019-05-27 10:33:27.452951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba55687c999'
down_revision = '30542f6de769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_column('comments', 'pitch_id')
    op.drop_constraint('users_post_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_post_id_fkey', 'users', 'posts', ['post_id'], ['id'])
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment_id')
    # ### end Alembic commands ###
